{
 "title": "Upstream and Downstream Replica Pods",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Upstream in same node with Downstream",
   "type": "timeseries",
   "description": "Pods in zone eu-west-8-b",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=\"aplaz\",pod=\"aplaz-667c69f547-wqtsw\"}[5m])) by (le))",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Upstream in different node but in same zone with Downstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=\"aplaz\",pod=\"aplaz-667c69f547-lnxcn\"}[5m])) by (le))",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Upstream in different node but in same zone with Downstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=\"aplaz\",pod=\"aplaz-667c69f547-pd586\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream in different zone with downstream (2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=\"aplaz\",pod=\"aplaz-667c69f547-jvvrz\"}[5m])) by (le))",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Application Latency - P99 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=\"default\",destination_workload=\"aplaz\"}[1m])) by (le))",
     "legendFormat": "{{destination_workload}} - P99 Latency"
    }
   ]
  }
 ]
}