apiVersion: v2
name: istio-chart
description: A Helm chart for Istio and Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: base
    version: "1.24.3"
    repository: https://istio-release.storage.googleapis.com/charts
    alias: istio-base
    condition: istio-base.enabled
  - name: istiod
    version: "1.24.3"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
  - name: prometheus
    version: "27.4.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: kube-netlag
    version: "1.0.0"
    repository: https://aposlaz.github.io/kube-netlag
    condition: kube-netlag.enabled
  # - name: kiali/kiali-operator
  #   version: "2.6.0"
  #   repository: https://kiali.org/helm-charts
  #   condition: kiali.enabled
