apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-controller
  # namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-controller
  template:
    metadata:
      labels:
        app: pod-controller
    spec:
      containers:
        - name: pod-controller
          image: alazidis/lpa-controller:0.0.3
          imagePullPolicy: Always
      serviceAccountName: full-access-sa
---
apiVersion: v1
kind: Service
metadata:
  name: pod-controller-svc
spec:
  selector:
    app: pod-controller
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort

