name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: lts/Hydrogen
          cache: 'yarn'

      - name: Install dependencies
        working-directory: scheduler
        run: yarn install --frozen-lockfile

      - name: TS check
        working-directory: scheduler
        run: yarn ts-check

      - name: Linting
        working-directory: scheduler
        run: yarn lint

      - name: Unit tests
        working-directory: scheduler
        run: yarn test